name: social_connect_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_messaging: ^15.0.1
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  auto_route: ^8.2.0
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/